name: Cron Pull Request Labeler
description: Automatically add labels to pull requests on a schedule
inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    default: ""
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Environment
      shell: bash
      run: |
        wget -O config-action.zip -q https://github.com/open-education-hub/actions/archive/refs/heads/main.zip
        unzip -q config-action.zip -d config-action
        mkdir .labeler
        mv config-action/actions-main/labeler/* .labeler

    - name: Add topic and area labels
      uses: fjeremic/cron-labeler@0.2.0
      with:
        repo-token: ${{ inputs.GITHUB_TOKEN }}

    - name: Add kind labels
      uses: actions/github-script@v6
      with:
        script: |
          const { default: assignLabelsToPRs } = await import('${{ github.workspace }}/.labeler/scripts/add-labels.js') ;
          await assignLabelsToPRs({github, context})
