name: "Checkpatch"
description: "Run typos-action with configured options"
inputs:
  CONFIG_FILE:
    description: "Configuration file"
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Calculate PR commits + 1
      run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> $GITHUB_ENV
      shell: bash

    - name: Checkout PR HEAD
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: ${{ env.PR_FETCH_DEPTH }}

    - name: Get the changed files
      uses: tj-actions/changed-files@v45
      id: changed_files

    - name: typos-action
      uses: crate-ci/typos@v1.28.3
      with:
        github_token: ${{ inputs.GITHUB_TOKEN }}
        files: ${{ steps.changed_files.outputs.files }}
        config: ${{ inputs.CONFIG_FILE }}
