name: 'Checkpatch'
description: 'Run checkpatch.pl with configured options'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    default: ''
    required: false

runs:
  using: 'composite'
  steps:
    - name: Calculate PR commits + 1
      run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> $GITHUB_ENV
      shell: bash

    - name: Checkout PR HEAD
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: ${{ env.PR_FETCH_DEPTH }}

    - name: Download checkpatch config file
      run: wget https://raw.githubusercontent.com/security-summer-school/actions/main/checkpatch/checkpatch.conf -O ${{github.workspace}}/.checkpatch.conf
      shell: bash

    - name: Run checkpatch review
      uses: webispy/checkpatch-action@v9
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}