name: "Spellcheck"
description: Check for spelling mistakes
inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Get Changed Files
      id: changed-files
      uses: tj-actions/changed-files@v37
      with:
        files: |
          **/*.md

    - name: Setup Environment
      shell: bash
      run: |
        wget -O config-action.zip -q https://github.com/open-education-hub/actions/archive/refs/heads/main.zip
        unzip -q config-action.zip -d config-action
        [ ! -f ".spellcheck.yml" ] && mv config-action/actions-main/spellcheck/config/spellcheck.yml .spellcheck.yml
        [ ! -f ".wordlist.txt" ] && mv config-action/actions-main/spellcheck/config/wordlist.txt .wordlist.txt

    - name: Spellcheck
      uses: rojopolis/spellcheck-github-actions@v0
      with:
        config_path: .spellcheck.yml
        source_files: "${{ steps.changed-files.outputs.all_changed_and_modified_files }}"
        task_name: Markdown
